services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      # - 7359:7359/udp
    volumes:
      - ./config/jellyfin/:/config
      - ./cache/jellyfin/:/cache
      - type: bind
        source: /home/jhonatan/Vídeos/Youtube
        target: /youtube
      - type: bind
        source: /home/jhonatan/Música
        target: /media2
        read_only: true
      - type: bind
        source: /home/jhonatan/Movies
        target: /movies
      - type: bind
        source: /home/jhonatan/Shows/
        target: /shows
    restart: 'unless-stopped'
    network_mode: host
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "media"

  tsdproxy:
    image: almeidapaulopt/tsdproxy:2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxy-data:/data
      - ./config:/config
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  tsdproxy-data:

